/* blocks.js: Block and item tables.
   Part of Thomas and the Block World. Classic script: every src/ file shares one global scope and loads in numeric order (see index.html). */
"use strict";

// ---------- BLOCKS ----------
const AIR = 0, GRASS = 1, DIRT = 2, STONE = 3, WOOD = 4, LEAVES = 5, SAND = 6, WATER = 7, LAVA = 8,
      FIRESTONE = 9, ENDSTONE = 10, PORTAL = 11, PLANKS = 12, COBBLE = 13, TORCH = 14, CHEST = 15, SNOW = 16, BRICK = 17, BED = 18, FIRE_CRYSTAL = 19, BOUNCE = 20, SPIKE = 21, ALARM = 22, FREDA = 23, MYCELIUM = 24, MUSHROOM = 25, CRYSTAL = 26, LAUNCH = 27, HEAL = 28, FROST = 29, TALLGRASS = 30, CDOOR = 31, QBLOCK = 32, PIPE = 33,
      COAL_ORE = 34, IRON_ORE = 35, GOLD_ORE = 36, DIAMOND_ORE = 37, FURNACE = 38, GLASS = 39, BIRCH_WOOD = 40, BIRCH_LEAVES = 41, SPRUCE_WOOD = 42, SPRUCE_LEAVES = 43, GRAVEL = 44, HAY = 45, PATH = 46, LANTERN = 47, STONEBRICK = 48,
      CRAFT_TABLE = 49, WOOL = 50, OBSIDIAN = 51, FENCE = 52, GATE = 53, GATE_OPEN = 54;
function C(hex) { const c = new THREE.Color(hex); return [c.r, c.g, c.b]; }
const BLOCKS = {
  [GRASS]:    { name: "Grass", solid: 1, opaque: 1, hard: 0.45, top: C(0x6cc24a), side: C(0x5aa83e), bot: C(0x8a5a2b), drop: DIRT, icon: "🟩" },
  [DIRT]:     { name: "Dirt", solid: 1, opaque: 1, hard: 0.4, top: C(0x8a5a2b), side: C(0x8a5a2b), bot: C(0x8a5a2b), drop: DIRT, icon: "🟫" },
  [STONE]:    { name: "Stone", solid: 1, opaque: 1, hard: 1.5, top: C(0x8d8d8d), side: C(0x8d8d8d), bot: C(0x8d8d8d), drop: COBBLE, tool: "pick", icon: "⬜" },
  [WOOD]:     { name: "Wood", solid: 1, opaque: 1, hard: 0.85, top: C(0x6e4a25), side: C(0x7a5630), bot: C(0x6e4a25), drop: WOOD, tool: "axe", icon: "🟧" },
  [LEAVES]:   { name: "Leaves", solid: 1, opaque: 1, hard: 0.2, top: C(0x3f9e3a), side: C(0x3f9e3a), bot: C(0x368a31), drop: LEAVES, icon: "🍃" },
  [SAND]:     { name: "Sand", solid: 1, opaque: 1, hard: 0.4, top: C(0xe3d7a0), side: C(0xe3d7a0), bot: C(0xd8c98c), drop: SAND, icon: "🟨" },
  [WATER]:    { name: "Water", solid: 0, opaque: 0, hard: 0, top: C(0x2f6fe0), side: C(0x2f6fe0), bot: C(0x2f6fe0), liquid: 1, icon: "🟦" },
  [LAVA]:     { name: "Lava", solid: 0, opaque: 1, hard: 0, top: C(0xff7a22), side: C(0xff5a14), bot: C(0xe2480c), liquid: 1, dmg: 4, icon: "🔥" },
  [FIRESTONE]:{ name: "Fire Stone", solid: 1, opaque: 1, hard: 1.4, top: C(0x6a1414), side: C(0x5a1414), bot: C(0x451010), drop: FIRESTONE, tool: "pick", icon: "🟥" },
  [ENDSTONE]: { name: "End Stone", solid: 1, opaque: 1, hard: 1.3, top: C(0xefe9c8), side: C(0xe6dfb6), bot: C(0xddd4a8), drop: ENDSTONE, tool: "pick", icon: "⬛" },
  [PLANKS]:   { name: "Planks", solid: 1, opaque: 1, hard: 0.7, top: C(0xb08a4f), side: C(0xb08a4f), bot: C(0xa07d45), drop: PLANKS, tool: "axe", icon: "🟫" },
  [COBBLE]:   { name: "Cobblestone", solid: 1, opaque: 1, hard: 1.5, top: C(0x7c7c7c), side: C(0x7c7c7c), bot: C(0x6f6f6f), drop: COBBLE, tool: "pick", icon: "⬜" },
  [TORCH]:    { name: "Torch", solid: 0, opaque: 0, hard: 0.1, top: C(0xffcf6b), side: C(0xffcf6b), bot: C(0x6e4a25), drop: TORCH, icon: "🕯️" },
  [CHEST]:    { name: "Chest", solid: 1, opaque: 1, hard: 0.8, top: C(0xb8863f), side: C(0x9c6f30), bot: C(0x7a5626), drop: CHEST, tool: "axe", icon: "🧰" },
  [SNOW]:     { name: "Snow", solid: 1, opaque: 1, hard: 0.35, top: C(0xeaf2f7), side: C(0xdfe9f0), bot: C(0xcfdae3), drop: SNOW, icon: "⬜" },
  [BRICK]:    { name: "Brick", solid: 1, opaque: 1, hard: 1.3, top: C(0x9c4a3c), side: C(0x99463a), bot: C(0x853c31), drop: BRICK, tool: "pick", icon: "🧱" },
  [BED]:      { name: "Bed", solid: 1, opaque: 1, hard: 0.4, top: C(0xd14b6a), side: C(0xb23b56), bot: C(0x7a5630), drop: BED, icon: "🛏️" },
  [FIRE_CRYSTAL]: { name: "Fire Crystal", solid: 1, opaque: 1, hard: 1.4, top: C(0xff8a1e), side: C(0xff5a14), bot: C(0xd23c08), drop: FIRE_CRYSTAL, tool: "pick", glow: 1, icon: "🔶" },
  [BOUNCE]:   { name: "Bounce Block", solid: 1, opaque: 1, hard: 0.3, top: C(0x49e06a), side: C(0x36c456), bot: C(0x2aa345), drop: BOUNCE, bouncy: 1, icon: "🟢" },
  [SPIKE]:    { name: "Spike Trap", solid: 1, opaque: 1, hard: 0.5, top: C(0xb8c0cc), side: C(0x8a929e), bot: C(0x6f7782), drop: SPIKE, spike: 1, icon: "🔺" },
  [ALARM]:    { name: "Alarm Bell", solid: 1, opaque: 1, hard: 0.6, top: C(0xffd24a), side: C(0xc9a227), bot: C(0x8a6f1a), drop: ALARM, alarm: 1, icon: "🔔" },
  [FREDA]:    { name: "Freda Block", solid: 1, opaque: 1, hard: 0.35, top: C(0xe23b2e), side: C(0xc62c22), bot: C(0x8a1c16), drop: FREDA, freda: 1, icon: "💥" },
  [MYCELIUM]: { name: "Mycelium", solid: 1, opaque: 1, hard: 0.5, top: C(0x9a6cb8), side: C(0x6a4a86), bot: C(0x8a5a2b), drop: DIRT, icon: "🟪" },
  [MUSHROOM]: { name: "Mushroom", solid: 1, opaque: 1, hard: 0.3, top: C(0xd0463a), side: C(0xc23a30), bot: C(0xe8e0d0), drop: MUSHROOM, icon: "🍄" },
  [CRYSTAL]:  { name: "Crystal", solid: 1, opaque: 1, hard: 1.2, top: C(0x76e4ff), side: C(0x4fc8ef), bot: C(0x36a8d0), drop: CRYSTAL, tool: "pick", glow: 1, icon: "🔷" },
  [LAUNCH]:   { name: "Launch Pad", solid: 1, opaque: 1, hard: 0.4, top: C(0xffd23d), side: C(0xff9a2e), bot: C(0xc97a1e), drop: LAUNCH, launch: 1, icon: "🚀" },
  [HEAL]:     { name: "Heal Block", solid: 1, opaque: 1, hard: 0.5, top: C(0x7cf0a0), side: C(0x4fd07e), bot: C(0x36a85e), drop: HEAL, heal: 1, glow: 1, icon: "💚" },
  [FROST]:    { name: "Frost Block", solid: 1, opaque: 1, hard: 0.5, top: C(0xbfe8ff), side: C(0x8fcff0), bot: C(0x6fb0d8), drop: FROST, frost: 1, glow: 1, icon: "🧊" },
  [TALLGRASS]:{ name: "Tall Grass", solid: 0, opaque: 0, hard: 0.1, top: C(0x57c93e), side: C(0x49b432), bot: C(0x3a9a28), drop: TALLGRASS, tallgrass: 1, icon: "🌿" },
  [CDOOR]:    { name: "Creature Door", solid: 1, opaque: 1, hard: 2, top: C(0x6a3df0), side: C(0x9b30ff), bot: C(0x3aa0ff), drop: CDOOR, glow: 1, icon: "🚪" },
  [QBLOCK]:   { name: "Question Block", solid: 1, opaque: 1, hard: 0.3, top: C(0xf2b530), side: C(0xe0a020), bot: C(0xb27a12), icon: "❓" },
  [PIPE]:     { name: "Warp Pipe", solid: 1, opaque: 1, hard: 1.6, top: C(0x2e9e46), side: C(0x37bf55), bot: C(0x217a34), drop: PIPE, icon: "🟢" },
  [COAL_ORE]: { name: "Coal Ore", solid: 1, opaque: 1, hard: 1.8, top: C(0x5c5c5e), side: C(0x5c5c5e), bot: C(0x5c5c5e), drop: 115, tool: "pick", minTier: 1, icon: "⚫" },
  [IRON_ORE]: { name: "Iron Ore", solid: 1, opaque: 1, hard: 2.2, top: C(0x8f8176), side: C(0x8f8176), bot: C(0x8f8176), drop: 35, tool: "pick", minTier: 2, icon: "🟤" },
  [GOLD_ORE]: { name: "Gold Ore", solid: 1, opaque: 1, hard: 2.3, top: C(0x9c8a52), side: C(0x9c8a52), bot: C(0x9c8a52), drop: 36, tool: "pick", minTier: 3, icon: "🟡" },
  [DIAMOND_ORE]: { name: "Diamond Ore", solid: 1, opaque: 1, hard: 2.8, top: C(0x6fa9ad), side: C(0x6fa9ad), bot: C(0x6fa9ad), drop: 118, tool: "pick", minTier: 3, glow: 1, icon: "💎" },
  [FURNACE]:  { name: "Furnace", solid: 1, opaque: 1, hard: 1.6, top: C(0x77777a), side: C(0x6a6a6d), bot: C(0x6a6a6d), drop: 38, tool: "pick", glow: 1, icon: "🔥" },
  [GLASS]:    { name: "Glass", solid: 1, opaque: 0, hard: 0.3, top: C(0xd8eef5), side: C(0xd8eef5), bot: C(0xd8eef5), drop: 39, icon: "🪟" },
  [BIRCH_WOOD]: { name: "Birch Log", solid: 1, opaque: 1, hard: 0.85, top: C(0xd8d2b8), side: C(0xe0dccf), bot: C(0xd8d2b8), drop: 4, tool: "axe", icon: "🪵" },
  [BIRCH_LEAVES]: { name: "Birch Leaves", solid: 1, opaque: 1, hard: 0.2, top: C(0x7fb24a), side: C(0x7fb24a), bot: C(0x6e9c40), drop: 5, icon: "🍃" },
  [SPRUCE_WOOD]: { name: "Spruce Log", solid: 1, opaque: 1, hard: 0.85, top: C(0x5a4028), side: C(0x4a3420), bot: C(0x5a4028), drop: 4, tool: "axe", icon: "🪵" },
  [SPRUCE_LEAVES]: { name: "Spruce Needles", solid: 1, opaque: 1, hard: 0.2, top: C(0x2f5a36), side: C(0x2f5a36), bot: C(0x27492d), drop: 5, icon: "🌲" },
  [GRAVEL]:   { name: "Gravel", solid: 1, opaque: 1, hard: 0.5, top: C(0x847e7a), side: C(0x847e7a), bot: C(0x847e7a), drop: 44, icon: "🪨" },
  [HAY]:      { name: "Hay Bale", solid: 1, opaque: 1, hard: 0.4, top: C(0xc9a23a), side: C(0xb8902e), bot: C(0xc9a23a), drop: 45, icon: "🌾" },
  [PATH]:     { name: "Dirt Path", solid: 1, opaque: 1, hard: 0.4, top: C(0x9b7a4a), side: C(0x8a5a2b), bot: C(0x8a5a2b), drop: 2, icon: "🟫" },
  [LANTERN]:  { name: "Lantern", solid: 1, opaque: 1, hard: 0.5, top: C(0x3a3a40), side: C(0xffc861), bot: C(0x3a3a40), drop: 47, tool: "pick", glow: 1, icon: "🏮" },
  [STONEBRICK]: { name: "Stone Bricks", solid: 1, opaque: 1, hard: 1.5, top: C(0x7f7f80), side: C(0x7f7f80), bot: C(0x7f7f80), drop: 48, tool: "pick", icon: "🧱" },
  [CRAFT_TABLE]: { name: "Crafting Table", solid: 1, opaque: 1, hard: 0.8, top: C(0xb08450), side: C(0xa0764a), bot: C(0xb08a4f), drop: 49, tool: "axe", icon: "🛠️" },
  [WOOL]:     { name: "Wool", solid: 1, opaque: 1, hard: 0.3, top: C(0xeeece6), side: C(0xeeece6), bot: C(0xeeece6), drop: 50, icon: "🧶" },
  [OBSIDIAN]: { name: "Obsidian", solid: 1, opaque: 1, hard: 9, top: C(0x1c1426), side: C(0x1c1426), bot: C(0x1c1426), drop: 51, tool: "pick", minTier: 4, icon: "⬛" },
  [FENCE]:    { name: "Fence", solid: 1, opaque: 0, hard: 0.7, top: C(0xb08a4f), side: C(0xb08a4f), bot: C(0xb08a4f), drop: 52, tool: "axe", tall: 1, icon: "🚧" },
  [GATE]:     { name: "Fence Gate", solid: 1, opaque: 0, hard: 0.7, top: C(0xb08a4f), side: C(0xb08a4f), bot: C(0xb08a4f), drop: 53, tool: "axe", tall: 1, gate: 1, icon: "🚪" },
  [GATE_OPEN]:{ name: "Fence Gate", solid: 0, opaque: 0, hard: 0.7, top: C(0xb08a4f), side: C(0xb08a4f), bot: C(0xb08a4f), drop: 53, tool: "axe", gate: 1, icon: "🚪" }
};
function isTall(id) { return id === FENCE || id === GATE; }             // fences and shut gates stand 1.5 blocks tall for collision
function isOpaque(id) { return id !== AIR && id !== WATER && id !== PORTAL && BLOCKS[id] && BLOCKS[id].opaque; }
function isSolidBlock(id) { return id !== AIR && id !== WATER && id !== PORTAL && BLOCKS[id] && BLOCKS[id].solid; }

// ITEMS (tools/food), ids offset 100
const I_HAND = 100, I_WPICK = 101, I_SPICK = 102, I_SWORD = 103, I_AXE = 104, I_FIRECHARM = 105, I_FIRESWORD = 106, I_LIGHTHAMMER = 107, I_BOOMPICK = 108, I_ICEBOW = 109, I_APPLE = 110, I_STICK = 111, I_SLIMELAUNCH = 112, I_CRYSTALSPEAR = 113, I_MACHINEGUN = 114,
      I_COAL = 115, I_IRON = 116, I_GOLD = 117, I_DIAMOND = 118, I_IPICK = 119, I_DPICK = 120, I_ISWORD = 121, I_DSWORD = 122, I_IAXE = 123, I_DAXE = 124, I_IARMOR = 125, I_DARMOR = 126, I_BREAD = 127, I_GAPPLE = 128,
      I_BOW = 129, I_ARROW = 130, I_FLINT = 131, I_FEATHER = 132, I_STRING = 133, I_SHEARS = 134, I_LEATHER = 135, I_LARMOR = 136,
      I_RAWBEEF = 137, I_STEAK = 138, I_RAWPORK = 139, I_PORKCHOP = 140, I_RAWMUTTON = 141, I_MUTTON = 142, I_RAWCHICKEN = 143, I_CHICKEN = 144, I_EGG = 145, I_PIE = 146,
      I_BUCKET = 147, I_WBUCKET = 148, I_LBUCKET = 149, I_MILK = 150, I_SHIELD = 151;
const ITEMS = {
  [I_WPICK]: { name: "Wood Pickaxe", tool: "pick", tier: 1, dmg: 2, dur: 60, icon: "⛏️" },
  [I_SPICK]: { name: "Stone Pickaxe", tool: "pick", tier: 2, dmg: 3, dur: 140, icon: "⛏️" },
  [I_SWORD]: { name: "Wood Sword", tool: "sword", tier: 1, dmg: 5, dur: 70, icon: "🗡️" },
  [I_AXE]:   { name: "Wood Axe", tool: "axe", tier: 1, dmg: 3, dur: 70, icon: "🪓" },
  [I_FIRECHARM]: { name: "Flame Charm", protect: "fire", icon: "🧿" },
  [I_FIRESWORD]: { name: "Flame Sword", tool: "sword", tier: 3, dmg: 9, dur: 600, special: "fire", icon: "🗡️" },
  [I_LIGHTHAMMER]: { name: "Lightning Hammer", tool: "hammer", tier: 2, dmg: 7, dur: 450, special: "lightning", icon: "🔨" },
  [I_BOOMPICK]: { name: "Boom Pickaxe", tool: "pick", tier: 2, dmg: 3, dur: 300, special: "boom", icon: "⛏️" },
  [I_ICEBOW]: { name: "Ice Bow", tool: "bow", dmg: 1, special: "ice", icon: "🏹" },
  [I_SLIMELAUNCH]: { name: "Slime Launcher", tool: "bow", dmg: 1, special: "slime", icon: "🟢" },
  [I_CRYSTALSPEAR]: { name: "Crystal Spear", tool: "sword", tier: 3, dmg: 8, dur: 650, special: "pierce", icon: "🔱" },
  [I_MACHINEGUN]: { name: "Machine Gun", tool: "gun", dmg: 4, icon: "🔫" },
  [I_APPLE]: { name: "Apple", food: 4, icon: "🍎" },
  [I_STICK]: { name: "Stick", icon: "➖" },
  [I_COAL]: { name: "Coal", icon: "⚫" },
  [I_IRON]: { name: "Iron Ingot", icon: "🔩" },
  [I_GOLD]: { name: "Gold Ingot", icon: "🥇" },
  [I_DIAMOND]: { name: "Diamond", icon: "💎" },
  [I_IPICK]: { name: "Iron Pickaxe", tool: "pick", tier: 3, dmg: 4, dur: 260, icon: "⛏️" },
  [I_DPICK]: { name: "Diamond Pickaxe", tool: "pick", tier: 4, dmg: 5, dur: 1000, icon: "⛏️" },
  [I_ISWORD]: { name: "Iron Sword", tool: "sword", tier: 3, dmg: 7, dur: 260, icon: "🗡️" },
  [I_DSWORD]: { name: "Diamond Sword", tool: "sword", tier: 4, dmg: 10, dur: 1000, icon: "🗡️" },
  [I_IAXE]: { name: "Iron Axe", tool: "axe", tier: 3, dmg: 5, dur: 260, icon: "🪓" },
  [I_DAXE]: { name: "Diamond Axe", tool: "axe", tier: 4, dmg: 7, dur: 1000, icon: "🪓" },
  [I_IARMOR]: { name: "Iron Armor", armor: 0.3, icon: "🛡️" },
  [I_DARMOR]: { name: "Diamond Armor", armor: 0.5, icon: "💠" },
  [I_BREAD]: { name: "Bread", food: 6, icon: "🍞" },
  [I_GAPPLE]: { name: "Golden Apple", food: 8, heal: 8, icon: "🍏" },
  [I_BOW]: { name: "Bow", tool: "bow", dmg: 2, dur: 240, draw: 1, icon: "🏹" },
  [I_ARROW]: { name: "Arrow", icon: "➶" },
  [I_FLINT]: { name: "Flint", icon: "🪨" },
  [I_FEATHER]: { name: "Feather", icon: "🪶" },
  [I_STRING]: { name: "String", icon: "🧵" },
  [I_SHEARS]: { name: "Shears", tool: "shears", dur: 180, icon: "✂️" },
  [I_LEATHER]: { name: "Leather", icon: "🟫" },
  [I_LARMOR]: { name: "Leather Armor", armor: 0.18, icon: "🦺" },
  [I_RAWBEEF]: { name: "Raw Beef", food: 3, icon: "🥩" },
  [I_STEAK]: { name: "Steak", food: 8, icon: "🍖" },
  [I_RAWPORK]: { name: "Raw Porkchop", food: 3, icon: "🥓" },
  [I_PORKCHOP]: { name: "Cooked Porkchop", food: 8, icon: "🍖" },
  [I_RAWMUTTON]: { name: "Raw Mutton", food: 2, icon: "🥩" },
  [I_MUTTON]: { name: "Cooked Mutton", food: 6, icon: "🍖" },
  [I_RAWCHICKEN]: { name: "Raw Chicken", food: 2, raw: 0.3, icon: "🍗" },
  [I_CHICKEN]: { name: "Cooked Chicken", food: 6, icon: "🍗" },
  [I_EGG]: { name: "Egg", icon: "🥚" },
  [I_PIE]: { name: "Farm Pie", food: 10, heal: 2, icon: "🥧" },
  [I_BUCKET]: { name: "Bucket", bucket: "empty", tool: "bucket", icon: "🪣" },
  [I_WBUCKET]: { name: "Water Bucket", bucket: WATER, tool: "bucket", icon: "🪣" },
  [I_LBUCKET]: { name: "Lava Bucket", bucket: LAVA, tool: "bucket", icon: "🪣" },
  [I_MILK]: { name: "Milk Bucket", food: 6, heal: 4, returns: I_BUCKET, tool: "bucket", icon: "🥛" },
  [I_SHIELD]: { name: "Shield", tool: "shield", dur: 320, icon: "🛡️" }
};
function isItem(id) { return id >= 100; }
function itemInfo(id) { return isItem(id) ? ITEMS[id] : BLOCKS[id]; }
function itemName(id) { const i = itemInfo(id); return i ? i.name : "?"; }
function itemIcon(id) { const i = itemInfo(id); return i ? (i.icon || "▪") : "▪"; }
